server:
  port: 8091
spring:
  #mongodb:
    #embedded:
      #version: 3.4.5
  data:
    mongodb:
      database: productdb
      host: localhost
      port: 27017
      username: root
      password: password
