version: '3.1'
services:
  mongo:
    image: mongo:latest # use the latest image.
    container_name: 'my-mongodb-container'
    restart: always
    ports:
      - '27017:27017'
    volumes: # optional to preserve the database after container is deleted
      - ~/mongo:/data/db

# Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"